dbt_code_project:
  outputs:
    dev:
      account: MZQPYFK-EF49460
      database: Jobtech_analysis
      password: login12345
      role: jobtech_dbt_role
      schema: warehouse
      threads: 1
      type: snowflake
      user: DBT_role
      warehouse: job_analysis_wh
  target: dev

ice_cream_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VOOOJGM-MD78538
      user: IrinaAntipina
      password: 5497ytACendVUNX
      role: ice_cream_dlt_role
      database: ice_cream
      warehouse: compute_wh
      schema: staging
      threads: 4

dbt_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../data_warehouse/job_ads.duckdb


dbt_duckdb_docker_local: 
  target: dev 
  outputs: 
    dev: 
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}" 

azure_cloud_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'data_warehouse/job_ads.duckdb') }}"