FROM python:3.11
WORKDIR /pipeline

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
COPY .dbt/ /root/.dbt/

ENV DBT_PROFILES_DIR=/root/.dbt
ENV DUCKDB_PATH=/mnt/data/job_ads.duckdb

CMD ["dagster", "dev", "-f", "orchestration/definitions.py", "-h", "0.0.0.0", "-p", "3000"]