FROM python:3.11
ENV DBT_PROFILES_DIR=/pipeline
WORKDIR /pipeline
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["dagster", "dev", "-f", "orchestration/definitions.py", "-h", "0.0.0.0", "-p", "3000"]